spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/welcheck_backend
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jwt:
    secret: dofaknfknadofoawekfandjfnoajdfjajdkfaowdnfoankwdfmklanldjfoaja  #jwt토큰키 - value

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

naver:
  id : seluo65@naver.com
  password : thafi05ai86

kakao:
  api:
    url: https://dapi.kakao.com/v2/local/search/address.json
    key: 2d9524e31a3d1d03d529d4588ae469b2

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
